version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
    ports:
      - "3307:3306"   # Use 3307 on host to avoid conflicts
    volumes:
      - ./sql:/docker-entrypoint-initdb.d  # Your SQL init scripts here
